// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function HandleFormSubmission(arg1:main.FormData):Promise<void>;

export function ReadDirFileCount(arg1:string,arg2:boolean):Promise<number>;
