// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function HandleFormSubmission(arg1) {
  return window['go']['main']['App']['HandleFormSubmission'](arg1);
}

export function ReadDirFileCount(arg1, arg2) {
  return window['go']['main']['App']['ReadDirFileCount'](arg1, arg2);
}
